CREATE TABLE departments
(
    id                int8 generated by default as identity,
    name              varchar(255) not null,
    description       varchar(255) not null,
    phone_number      varchar(255) not null,
    date_of_formation timestamp    not null,

    primary key (id)
);

CREATE TABLE employees
(
    id                 int8 generated by default as identity,
    full_name          varchar(255),
    date_of_birth      timestamp    not null,
    phone_number       varchar(255) not null,
    email_address      varchar(255) not null,
    position           varchar(30)  not null,
    date_of_employment timestamp    not null,
    department_id      int8 default null,

    primary key (id),
    foreign key (department_id) references departments (id)
);

CREATE TABLE vehicles
(
    id            int8 generated by default as identity,
    model         varchar(255) not null,
    number        varchar(255) not null unique,
    vin           varchar(255) not null unique,
    year_of_issue int4         not null,
    employee_id   int8 default null,

    primary key (id),
    foreign key (employee_id) references employees (id)
);

CREATE TABLE service_orders
(
    id           int8 generated by default as identity,
    service_name varchar(30) not null,
    start_time   timestamp   not null,
    end_time     timestamp   not null,
    vehicle_id   int8        not null,
    employee_id  int8        not null,

    primary key (id),
    foreign key (vehicle_id) references vehicles (id),
    foreign key (employee_id) references employees (id)
);